<a href="https://colab.research.google.com/github/Deeks900/GenAIBootcamp/blob/main/Gensim.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install gensim 'numpy<1.26'

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 60.6/60.6 kB 1.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 26.7/26.7 MB 16.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 18.2/18.2 MB 34.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 38.6/38.6 MB 10.0 MB/s eta 0:00:00
  Attempting uninstall: numpy
    Found existing installation: numpy 2.0.2
    Uninstalling numpy-2.0.2:
      Successfully uninstalled numpy-2.0.2
  Attempting uninstall: scipy
    Found existing installation: scipy 1.14.1
    Uninstalling scipy-1.14.1:
      Successfully uninstalled scipy-1.14.1
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
blosc2 3.3.0 requires numpy>=1.26, but you have numpy 1.25.2 which is incompatible.
tensorflow 2.18.0 requires numpy<2.1.0,>=1.26.0, but you have numpy 1.25.2 which is incompatible.
thinc 8.3.6 requires numpy<

In [13]:
import gensim
import torch

In [2]:
%%writefile get_data.sh
wget -O yelp.csv  https://www.dropbox.com/scl/fi/dr6xmgw59kliq74gcd340/yelp.csv?rlkey=la6ue9a899v54f04eu92lbmlx&st=kjg7pmvm&dl=0

Overwriting get_data.sh


In [4]:
!bash get_data.sh

--2025-04-24 06:12:56--  https://www.dropbox.com/scl/fi/dr6xmgw59kliq74gcd340/yelp.csv?rlkey=la6ue9a899v54f04eu92lbmlx
Resolving www.dropbox.com (www.dropbox.com)... 162.125.13.18, 2620:100:6050:18::a27d:b12
Connecting to www.dropbox.com (www.dropbox.com)|162.125.13.18|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://uceded5c85b6a2c2e94a235f5144.dl.dropboxusercontent.com/cd/0/inline/CoZ0BYlrv_nCR1WpdOM3q4g-VpmT_SUeta410k-WNv2z6O-kgFkph5pyVS5Iz7jT4Sy3s0fM-X3d_btuXxGmX4ZNKYm7666-OMI4KgysxcAEvKAHjEg1Kfw2UKhgUVHKt1jUKpOsal7W56kwhaw61V5O/file# [following]
--2025-04-24 06:12:56--  https://uceded5c85b6a2c2e94a235f5144.dl.dropboxusercontent.com/cd/0/inline/CoZ0BYlrv_nCR1WpdOM3q4g-VpmT_SUeta410k-WNv2z6O-kgFkph5pyVS5Iz7jT4Sy3s0fM-X3d_btuXxGmX4ZNKYm7666-OMI4KgysxcAEvKAHjEg1Kfw2UKhgUVHKt1jUKpOsal7W56kwhaw61V5O/file
Resolving uceded5c85b6a2c2e94a235f5144.dl.dropboxusercontent.com (uceded5c85b6a2c2e94a235f5144.dl.dropboxusercontent.com)... 162.125.4.15, 2620:100

In [7]:
import pandas as pd
path = './yelp.csv'
yelp = pd.read_csv(path)[:1000]
yelp

business_id        date               review_id  stars  \
0    9yKzy9PApeiPPOUJEtnvkg  2011-01-26  fWKvX83p0-ka4JS3dc6E5A      5   
1    ZRJwVLyzEJq1VAihDhYiow  2011-07-27  IjZ33sJrzXqU-0X6U8NwyA      5   
2    6oRAC4uyJCsJl1X0WZpVSA  2012-06-14  IESLBzqUCLdSzSqm0eCSxQ      4   
3    _1QQZuf4zZOyFCvXc0o6Vg  2010-05-27  G-WvGaISbqqaMHlNnByodA      5   
4    6ozycU1RpktNG2-1BroVtw  2012-01-05  1uJFq2r5QfJG_6ExMRCaGw      5   
..                      ...         ...                     ...    ...   
995  -PA_1J9JzxLcluTOw2gZjw  2012-04-27  MNjiCQavIbMZpuBGSbGp9Q      1   
996  bRk44ShCT0osos-1xaTRyA  2008-09-21  eYtmkXM7xLwb0w-OpAqIIQ      5   
997  roTWGaU-RcJ06l8cjFw7xQ  2007-11-27  KpnYRPGPVAAh3tl8NUuGHg      2   
998  V2isTBBfO0NgLzXO9oq1Mg  2007-08-13  pehsPum9iW6DVyWil6WhFQ      5   
999  WUZxVr_CaRqEQgzvyeK5tw  2012-03-25  1v3rPVXx6RDWjgIUTfVLpw      5   

                                                  text    type  \
0    My wife took me here on my birthday for breakf...  review   
1    I have no idea why some people give bad review...  review   
2    love the gyro plate. Rice is so good and I als...  review   
3    Rosie, Dakota, and I LOVE Chaparral Dog Park!!...  review   
4    General Manager Scott Petello is a good egg!!!...  review   
..                                                 ...     ...   
995  Not worth the money. Food was average and the ...  review   
996  I love me some Dobson Ranch.  As far as munici...  review   
997  I don't know why i have been here more than on...  review   
998  Mouth watering. That's all I have to say.\n\nT...  review   
999  IKEA is so much fun. It's a little bit of a wa...  review   

                    user_id  cool  useful  funny  
0    rLtl8ZkDX5vH5nAx9C3q5Q     2       5      0  
1    0a2KyEL0d3Yb1V6aivbIuQ     0       0      0  
2    0hT2KtfLiobPvh6cDC8JQg     0       1      0  
3    uZetl9T0NcROGOyFfughhg     1       2      0  
4    vYmM4KTsC8ZfQBg-j5MWkw     0       0      0  
..                      ...   ...     ...    ...  
995  mCE9nD2NnYrokWMMMDoEdw     0       1      0  
996  dQO0tQISZyb9L4d5ASnXyQ     0       1      0  
997  GAW_mbLDbIoZQ0V0ZhWK8Q     0       0      0  
998  9FbgqZ5u9WTLAs28nNafIQ     1       0      0  
999  WxO2x4xGbHfeWfU_MbuzTQ     0       2      0  

[1000 rows x 10 columns]

In [35]:
text = yelp['text'].to_list()
text[0]


'My wife took me here on my birthday for breakfast and it was excellent.  The weather was perfect which made sitting outside overlooking their grounds an absolute pleasure.  Our waitress was excellent and our food arrived quickly on the semi-busy Saturday morning.  It looked like the place fills up pretty quickly so the earlier you get here the better.\n\nDo yourself a favor and get their Bloody Mary.  It was phenomenal and simply the best I\'ve ever had.  I\'m pretty sure they only use ingredients from their garden and blend them fresh when you order it.  It was amazing.\n\nWhile EVERYTHING on the menu looks excellent, I had the white truffle scrambled eggs vegetable skillet and it was tasty and delicious.  It came with 2 pieces of their griddled bread with was amazing and it absolutely made the meal complete.  It was the best "toast" I\'ve ever had.\n\nAnyway, I can\'t wait to go back!'

In [36]:
text = [gensim.utils.simple_preprocess(line) for line in text]
print(text[0])

['my', 'wife', 'took', 'me', 'here', 'on', 'my', 'birthday', 'for', 'breakfast', 'and', 'it', 'was', 'excellent', 'the', 'weather', 'was', 'perfect', 'which', 'made', 'sitting', 'outside', 'overlooking', 'their', 'grounds', 'an', 'absolute', 'pleasure', 'our', 'waitress', 'was', 'excellent', 'and', 'our', 'food', 'arrived', 'quickly', 'on', 'the', 'semi', 'busy', 'saturday', 'morning', 'it', 'looked', 'like', 'the', 'place', 'fills', 'up', 'pretty', 'quickly', 'so', 'the', 'earlier', 'you', 'get', 'here', 'the', 'better', 'do', 'yourself', 'favor', 'and', 'get', 'their', 'bloody', 'mary', 'it', 'was', 'phenomenal', 'and', 'simply', 'the', 'best', 've', 'ever', 'had', 'pretty', 'sure', 'they', 'only', 'use', 'ingredients', 'from', 'their', 'garden', 'and', 'blend', 'them', 'fresh', 'when', 'you', 'order', 'it', 'it', 'was', 'amazing', 'while', 'everything', 'on', 'the', 'menu', 'looks', 'excellent', 'had', 'the', 'white', 'truffle', 'scrambled', 'eggs', 'vegetable', 'skillet', 'and', 'i

In [37]:
from gensim.models import Word2Vec
w2v_model = Word2Vec(sentences=text, vector_size=50, min_count=1, window=5, workers=4, epochs=10)

In [38]:
vocab_size = len(w2v_model.wv.key_to_index)
w2v_model.wv.key_to_index['[UNK]'] = vocab_size
vocab_size += 1
vocab_size

9724

In [39]:
vector = w2v_model.wv.get_vector('wine')
vector, vector.shape

(array([-0.34774062, -0.12575147, -0.03768789,  0.18791753, -0.29774296,
        -0.68384105,  0.85120505,  1.1557896 , -1.0645304 , -0.4173458 ,
        -0.12914152, -0.65599537,  0.15204945,  0.15141368, -0.23742573,
         0.18253098,  0.5774417 ,  0.1485084 , -1.2530594 , -1.0194821 ,
         0.13185795,  0.76836216,  1.2709895 , -0.12023711,  0.3655137 ,
         0.17789964, -0.6195296 ,  0.58738154, -1.0186607 ,  0.0740547 ,
         0.1823399 , -0.40017015,  0.08451344,  0.18460858, -0.9546881 ,
         0.2722504 ,  0.6067928 , -0.06885776,  0.01025335, -0.41368118,
         0.69072527,  0.07193103, -0.57239914, -0.24979317,  1.3008344 ,
        -0.13514236, -0.33186102, -0.5662928 ,  0.85928756,  0.0255928 ],
       dtype=float32),
 (50,))

In [42]:
similars = w2v_model.wv.most_similar('pizza', topn=10)
similars

[('fast', 0.992986798286438),
 ('absolutely', 0.9898867607116699),
 ('wonderful', 0.9897540807723999),
 ('social', 0.9896401166915894),
 ('pleasant', 0.9895107746124268),
 ('perfect', 0.988762378692627),
 ('ambiance', 0.9875544309616089),
 ('fabulous', 0.9875140190124512),
 ('rude', 0.9868929386138916),
 ('fantastic', 0.9867562055587769)]

In [43]:
# THIS IS VERY INTERNAL YOU WILL NEVER DO THIS

import numpy as np

def cosine_similarity(vec1, vec2):
  """Calculates the cosine similarity between two vectors.

  Args:
      vec1: The first vector.
      vec2: The second vector.

  Returns:
      The cosine similarity between the two vectors.
  """
  dot_product = np.dot(vec1, vec2)
  norm_vec1 = np.linalg.norm(vec1)
  norm_vec2 = np.linalg.norm(vec2)
  return dot_product / (norm_vec1 * norm_vec2)

In [ ]:
pizza_vector = w2v_model.wv.get_vector('pizza')
for similar in similars:
  word, score = similar
  print('\n --------------------\n')
  print(word, w2v_model.wv.get_vector(word))
  print('\n --------------------\n')
  distance = cosine_similarity(pizza_vector, w2v_model.wv.get_vector(word))
  print(distance, score)
  print('\n --------------------\n')


 --------------------

wonderful [-0.3194134  -0.14930853  0.01371251  0.1169365  -0.20428702 -0.4557146
  0.7541973   1.096093   -0.8463955  -0.18580683 -0.00270726 -0.55525076
  0.08438654  0.25508708 -0.2611699   0.33014512  0.5973996   0.04368879
 -1.1788788  -0.917382    0.18795404  0.5650465   1.1926315  -0.19280612
  0.25906935  0.09980077 -0.39434126  0.5068238  -0.94887567  0.01519528
  0.02730107 -0.282501   -0.13578577  0.14294127 -0.9318337   0.22349681
  0.59391516 -0.10202914  0.03946726 -0.50686926  0.39040756  0.20286554
 -0.51593965 -0.26338866  1.1027036  -0.07053535 -0.29076532 -0.41759598
  0.6807579   0.18780364]

 --------------------

0.9932764 0.9932765364646912

 --------------------


 --------------------

fast [-0.223226   -0.11002081 -0.07885289  0.10090174 -0.13143383 -0.32377407
  0.5351074   0.7767229  -0.5993233  -0.16182075 -0.02494974 -0.37500137
  0.0597415   0.22003251 -0.21061115  0.2213217   0.44952056  0.05997888
 -0.8477583  -0.6374747   0.1237

In [51]:
weights = w2v_model.wv.vectors

In [54]:
weights.shape
weights[0]

array([-0.42927435, -0.57361734,  0.40735415,  0.48028034, -0.866094  ,
       -0.09657328,  1.0545957 ,  1.811931  , -1.3296527 , -0.16413584,
        0.7615492 , -0.07932679, -0.05488338,  0.34791225, -0.36688027,
        0.1099354 ,  0.33296198, -0.53797287, -1.3405604 , -1.1849711 ,
        0.29314274,  0.7056926 ,  1.4635384 , -0.02619511,  1.1557313 ,
       -0.0769943 , -0.38515338,  0.7423464 , -1.559188  ,  0.21903718,
       -0.07529634, -0.64063954,  0.0069312 ,  0.25994667, -1.8412164 ,
        0.8509773 ,  0.924622  , -0.20838198,  0.04741691, -1.3580401 ,
       -0.35339665,  0.63397694, -1.1730269 , -0.43532106,  1.3407277 ,
       -0.8692983 , -0.58477366, -0.6698204 ,  1.1364765 ,  1.0758246 ],
      dtype=float32)

In [59]:
# prompt: sample a random key from dict key_to_index

import random

random_word = random.choice(list(w2v_model.wv.key_to_index.keys()))
random_word


'ph'

In [60]:
id_of_word = w2v_model.wv.key_to_index[random_word]
id_of_word

7790

In [61]:
weights[id_of_word]

array([-0.02326492,  0.0122895 , -0.00565823, -0.00540835, -0.02422041,
       -0.00623409,  0.02180829,  0.0356924 , -0.04104241, -0.01648421,
        0.00437009, -0.02698006, -0.0056957 ,  0.00087074, -0.02639413,
       -0.01426575, -0.00611942,  0.02706714, -0.03496563, -0.03839802,
        0.00413834,  0.04605081,  0.03898484, -0.01042808,  0.04548173,
        0.02467052, -0.02549961,  0.0145174 , -0.02534391, -0.00123294,
        0.01942801,  0.00330026, -0.00279956, -0.00872624, -0.00310115,
        0.01489886,  0.01149087,  0.00454736,  0.01539328, -0.04371914,
        0.0653222 , -0.03204485, -0.01634298,  0.01484827,  0.04857803,
        0.01349846,  0.00623626,  0.00948903,  0.0153308 , -0.03314719],
      dtype=float32)

In [62]:
w2v_model.wv.get_vector(random_word)

array([-0.02326492,  0.0122895 , -0.00565823, -0.00540835, -0.02422041,
       -0.00623409,  0.02180829,  0.0356924 , -0.04104241, -0.01648421,
        0.00437009, -0.02698006, -0.0056957 ,  0.00087074, -0.02639413,
       -0.01426575, -0.00611942,  0.02706714, -0.03496563, -0.03839802,
        0.00413834,  0.04605081,  0.03898484, -0.01042808,  0.04548173,
        0.02467052, -0.02549961,  0.0145174 , -0.02534391, -0.00123294,
        0.01942801,  0.00330026, -0.00279956, -0.00872624, -0.00310115,
        0.01489886,  0.01149087,  0.00454736,  0.01539328, -0.04371914,
        0.0653222 , -0.03204485, -0.01634298,  0.01484827,  0.04857803,
        0.01349846,  0.00623626,  0.00948903,  0.0153308 , -0.03314719],
      dtype=float32)

## Way 1 of doing NLP (no one dows this)

In [64]:
def get_max_review_length(text):
  max_length = 0
  for review in text:
    if len(review) > max_length:
      max_length = len(review)
  return max_length

max_review_length = get_max_review_length(text)
max_review_length

841

In [65]:
X = np.zeros((len(text), max_review_length, 50))

In [66]:
for row_ix, review in enumerate(text):
  for col_ix, word in enumerate(review):
      if word not in w2v_model.wv.key_to_index:
        word = '[UNK]'
      X[row_ix, col_ix] = w2v_model.wv.get_vector(word)

In [ ]:
X.shape  # ( review, word, rep of review in w2v)

(1000, 841, 50)

## Way 2 (Everyone does this)

In [68]:
weights = torch.tensor(w2v_model.wv.vectors)
vocab_size, embedding_dim = weights.shape
X = np.zeros((len(text), max_review_length))

In [ ]:
weights.dtype

torch.float32

In [ ]:
vocab_size, embedding_dim

(9723, 50)

In [ ]:
X = np.zeros((len(text), max_review_length))
for row_ix, review in enumerate(text):
  for col_ix, word in enumerate(review):
      if word not in w2v_model.wv.key_to_index:
        token = 0
      else:
        token = w2v_model.wv.key_to_index[word]
      X[row_ix, col_ix] = token

In [ ]:
X_train = torch.tensor(X).to(torch.long)
X_train

tensor([[  13,  423,  212,  ...,    0,    0,    0],
        [  17,   64,  819,  ...,    0,    0,    0],
        [  71,    0,  941,  ...,    0,    0,    0],
        ...,
        [  61,  110,  263,  ...,    0,    0,    0],
        [ 675, 1403,    9,  ...,    0,    0,    0],
        [3202,    6,   22,  ...,    0,    0,    0]])

In [ ]:
from torch.nn import Embedding, Linear, Sequential, LogSoftmax

model = Sequential(
    Embedding.from_pretrained(embeddings=weights, freeze=True, padding_idx=0)
)


In [ ]:
response = model(X_train[:2])
X_train[:2].shape, response.shape

(torch.Size([2, 841]), torch.Size([2, 841, 50]))

In [ ]:
random_index_to_check = X_train[0][2]

In [ ]:
random_index_to_check, w2v_model.wv.index_to_key[random_index_to_check]

(tensor(212), 'took')

In [ ]:
w2v_model.wv.get_vector('took')

array([-0.28980276, -0.24130622,  0.16393535,  0.35079327, -0.35429332,
       -0.7192967 ,  0.975764  ,  1.0859263 , -0.9832944 ,  0.02724573,
        0.140747  , -0.7413968 ,  0.16827437,  0.44623685, -0.37493804,
        0.01568245,  0.45581055,  0.33517775, -0.9929629 , -0.88486826,
        0.36816835,  0.48068637,  1.2302791 , -0.38737202,  0.860768  ,
        0.32857955, -0.89379334,  0.7380525 , -0.87955624, -0.10983314,
        0.7086394 , -0.01664973,  0.24551617,  0.1596724 , -0.59546345,
        0.12640975,  0.4345531 , -0.19166999,  0.7300471 , -0.53412646,
        0.445934  , -0.2913586 , -0.46171847, -0.25730205,  1.5941459 ,
        0.11901267,  0.11724807, -0.6667303 ,  0.49652198,  0.07485989],
      dtype=float32)

In [ ]:
list(model.named_parameters())[0][1][random_index_to_check]

tensor([-0.2898, -0.2413,  0.1639,  0.3508, -0.3543, -0.7193,  0.9758,  1.0859,
        -0.9833,  0.0272,  0.1407, -0.7414,  0.1683,  0.4462, -0.3749,  0.0157,
         0.4558,  0.3352, -0.9930, -0.8849,  0.3682,  0.4807,  1.2303, -0.3874,
         0.8608,  0.3286, -0.8938,  0.7381, -0.8796, -0.1098,  0.7086, -0.0166,
         0.2455,  0.1597, -0.5955,  0.1264,  0.4346, -0.1917,  0.7300, -0.5341,
         0.4459, -0.2914, -0.4617, -0.2573,  1.5941,  0.1190,  0.1172, -0.6667,
         0.4965,  0.0749])

In [ ]:
response[0][2]

tensor([-0.2898, -0.2413,  0.1639,  0.3508, -0.3543, -0.7193,  0.9758,  1.0859,
        -0.9833,  0.0272,  0.1407, -0.7414,  0.1683,  0.4462, -0.3749,  0.0157,
         0.4558,  0.3352, -0.9930, -0.8849,  0.3682,  0.4807,  1.2303, -0.3874,
         0.8608,  0.3286, -0.8938,  0.7381, -0.8796, -0.1098,  0.7086, -0.0166,
         0.2455,  0.1597, -0.5955,  0.1264,  0.4346, -0.1917,  0.7300, -0.5341,
         0.4459, -0.2914, -0.4617, -0.2573,  1.5941,  0.1190,  0.1172, -0.6667,
         0.4965,  0.0749])

Let's make the model classifier

In [ ]:
# prompt: generate MeanLayer from (nn.Module) that applies mean over axis=1

import torch.nn as nn

class MeanLayer(nn.Module):
    def forward(self, x):
        return torch.mean(x, dim=1)


In [ ]:
model  = Sequential(
    Embedding.from_pretrained(embeddings=weights, freeze=True, padding_idx=0),
    # add layers to get better re[presentation per word

    #pass from representation pof words (3 d) to rep of review (2d)

    MeanLayer(),

    # final part
    Linear(in_features=embedding_dim, out_features=2), # 2 classes,
    LogSoftmax(dim=1)
)
model

Sequential(
  (0): Embedding(9723, 50, padding_idx=0)
  (1): MeanLayer()
  (2): Linear(in_features=50, out_features=2, bias=True)
  (3): LogSoftmax(dim=1)
)

In [ ]:
model(X_train[:2]).shape

torch.Size([2, 2])