<a href="https://colab.research.google.com/github/Deeks900/GenAIBootcamp/blob/main/PyTorch_1_Exercise_PyTorch_Tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Import the __`torch`__ package

In [3]:
import torch as pt
pt.manual_seed(0);

## Create a vector of ten zeros

In [4]:
ans = pt.zeros(10)
print(ans)
print(type(ans))

tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])
<class 'torch.Tensor'>


## Create a vector of size ten with nine zeros and a 1 in the fifth position

In [ ]:
tensor = pt.zeros(10)
tensor[4] = 1
tensor

tensor([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

## Create a vector with values ranging from 10 to 49

In [5]:
v = pt.arange(10, 50)


## Reverse the previous vector

In [ ]:
reversed(v)

tensor([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33, 32,
        31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15, 14,
        13, 12, 11, 10])

## Create a 3x3 matrix with values ranging from 0 to 8

In [6]:
# prompt: create a 3*3 matrix with values ranging from 0 to 8

matrix = pt.arange(0, 9).reshape(3, 3)
matrix


tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])

## Find the indices of the non-zero elements of the following array:

In [ ]:
v = pt.tensor([1, 2, 0, 0, 4, 0]) # Given
pt.nonzero(v)


tensor([[0],
        [1],
        [4]])

## Create a 5x5 identity matrix

In [7]:
# prompt: create a 5*5 identity matrix

pt.rand(5, 5)


tensor([[0.4963, 0.7682, 0.0885, 0.1320, 0.3074],
        [0.6341, 0.4901, 0.8964, 0.4556, 0.6323],
        [0.3489, 0.4017, 0.0223, 0.1689, 0.2939],
        [0.5185, 0.6977, 0.8000, 0.1610, 0.2823],
        [0.6816, 0.9152, 0.3971, 0.8742, 0.4194]])

## Create a 3x3x3 array with random values

In [11]:
# prompt: ## Create a 3x3x3 array with random values

v = pt.rand(3, 3, 3)
v


tensor([[[0.1872, 0.0340, 0.9442],
         [0.8802, 0.0012, 0.5936],
         [0.4158, 0.4177, 0.2711]],

        [[0.6923, 0.2038, 0.6833],
         [0.7529, 0.8579, 0.6870],
         [0.0051, 0.1757, 0.7497]],

        [[0.6047, 0.1100, 0.2121],
         [0.9704, 0.8369, 0.2820],
         [0.3742, 0.0237, 0.4910]]])

## Find the minimum and maximum values generated in the previous step

In [12]:
v.min(), v.max()


(tensor(0.0012), tensor(0.9704))

In [15]:
pt.max(v, dim=2)

torch.return_types.max(
values=tensor([[0.9442, 0.8802, 0.4177],
        [0.6923, 0.8579, 0.7497],
        [0.6047, 0.9704, 0.4910]]),
indices=tensor([[2, 0, 1],
        [0, 1, 2],
        [0, 0, 2]]))

## Create a vector with 30 random values and find its mean

In [ ]:
# prompt: Create a vector with 30 random values and find its mean

v = pt.rand(30)
v.mean()


## Create a 5x5 2d array with 1s around the edges and 0s in the middle

In [ ]:
# Create a 5x5 tensor filled with zeros
tensor = pt.zeros(5, 5)

# Set the edges to 1
tensor[0, :] = 1  # First row
tensor[-1, :] = 1  # Last row
tensor[:, 0] = 1  # First column
tensor[:, -1] = 1  # Last column

tensor


tensor([[1., 1., 1., 1., 1.],
        [1., 0., 0., 0., 1.],
        [1., 0., 0., 0., 1.],
        [1., 0., 0., 0., 1.],
        [1., 1., 1., 1., 1.]])

## Try to predict the output of each of the following cells before running them

In [16]:
0 * float('nan')

nan

In [17]:
float('nan') == float('nan')

False

In [18]:
float('inf') > float('nan')

False

In [19]:
float('nan') - float('nan')

nan

In [20]:
0.3 == 3 * 0.1

False

In [21]:
pt.tensor([0]) // pt.tensor([0]) #crashes the kernel :) continue with the next cell

RuntimeError: ZeroDivisionError

In [ ]:
import torch as pt #this is in case you crashed on the previous cell
pt.tensor([0]) // pt.tensor([0.0])

In [ ]:
nan_scalar = pt.tensor([float('nan')])

pt.isnan(nan_scalar)

In [ ]:
pt.tensor([0]) / pt.tensor([0.0])

## Find the integer part of the following array using four different methods:

In [22]:
a = pt.randn((10,), dtype = pt.float32)
a

tensor([ 1.7340, -0.1336, -0.8351,  0.9855, -0.0052, -0.0944, -1.1236, -0.6513,
         0.5693,  0.1782])

## Create a vector of 10 values from 0 to 1, both included

## Create a vector of size 10 with values ranging from 0 to 1, both excluded

## Subtract the mean of each row of the following matrix

In [ ]:
m = pt.rand(3, 3)
m

## Add 1,000,000 numbers together using __`torch`__ vectorized operations

## Create a 4x4 array of the first 16 powers of 3